// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://declymxlblaoeexpgfzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlY2x5bXhsYmxhb2VleHBnZnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzY4ODgsImV4cCI6MjA2MzY1Mjg4OH0.k122AH1XtDamIXr8c8hAnHSqlXmwMt7q65jbaQ7p43M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);